name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_VERSION: "0.6.5" # Pin uv version to avoid breaking changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Create venv and install dependencies
        run: |
          # Create venv and install dependencies
          uv venv
          source .venv/bin/activate
          uv sync --group dev --frozen

      - name: Python format
        run: uvx ruff format --diff .

      - name: Python lint
        run: uvx ruff check .
