name: Publish to PyPI

on:
  release:
    types: [published]

env:
  UV_VERSION: "0.6.5" # Pin uv version to avoid breaking changes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/supabase-mcp-server/
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Create venv and install dependencies
        run: |
          # Create venv and install dependencies
          uv venv
          source .venv/bin/activate
          uv sync --group dev --frozen

      - name: Build package
        run: uv build --no-sources

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
